### ISSUE TITLE
Use cljsjs/msgpack-lite

### ISSUE THREAD

**Issue by jsa-aerial** [christo-auer/cljs-msgpack-lite#1]
JS msgpack-lite is packaged in CLJSJS repo:

https://github.com/cljsjs/packages/tree/master/msgpack-lite

Using it would remove the explicit npm stuff in cljs-msgpack-lite, and users of cljs-msgpack-lite would only need to include cljs-msgpack-lite as a dependency in their project.

Seems like a significant improvement to both the dev and user experience.

Any reason why this hasn't been done??

**Comment by christo-auer** [comment]
Good point, thanks! No, there has not been any particular reason --- just plain ignorance :-)

I've just deployed version 0.1.6 where this should be fixed.

**Comment by jsa-aerial** [comment]
Cool! Thanks for the quick turnaround - and thanks for the lib - really nice!
